<?php

namespace Database\Seeders;

use App\Models\Vocabulary\Word;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * First batch of the vocabulary expansion (target: 2000 new words total,
 * added in batches of ~200-300 with two new thematic categories per
 * batch). Skips any English word that already exists in the words table
 * (case-insensitive) so the seeder is safe to re-run.
 */
class VocabularyBatch1Seeder extends Seeder
{
    public function run(): void
    {
        $existing = Word::pluck('word')->map(fn ($w) => Str::lower($w))->flip();

        $created = 0;
        $skipped = 0;

        foreach ($this->entries() as $row) {
            [$en, $ipa, $ru, $example, $difficulty, $category] = $row;

            if (isset($existing[Str::lower($en)])) {
                $skipped++;

                continue;
            }

            $word = Word::create([
                'word' => $en,
                'transcription' => $ipa,
                'example' => $example,
                'difficulty' => $difficulty,
                'category' => $category,
            ]);

            $word->translations()->create([
                'language' => 'ru',
                'translation' => $ru,
                'example' => $example,
            ]);

            $existing[Str::lower($en)] = true;
            $created++;
        }

        $this->command?->info("VocabularyBatch1Seeder: +{$created} words, {$skipped} skipped as already existing.");
    }

    /**
     * @return array<int, array{0: string, 1: string, 2: string, 3: string, 4: int, 5: string}>
     */
    private function entries(): array
    {
        $science = 'Наука и исследования';
        $tech = 'Компьютеры и интернет';

        return [
            // ===== Наука и исследования (Science and Research) =====
            ['atom', 'ˈætəm', 'атом', 'Everything is made of atoms.', 5, $science],
            ['molecule', 'ˈmɒlɪkjuːl', 'молекула', 'A water molecule has two hydrogen atoms.', 6, $science],
            ['cell', 'sel', 'клетка', 'The human body has trillions of cells.', 4, $science],
            ['gene', 'dʒiːn', 'ген', 'This gene controls eye colour.', 6, $science],
            ['DNA', 'ˌdiː.enˈeɪ', 'ДНК', 'DNA carries genetic information.', 6, $science],
            ['chromosome', 'ˈkrəʊməsəʊm', 'хромосома', 'Humans have 46 chromosomes.', 8, $science],
            ['evolution', 'ˌiːvəˈluːʃən', 'эволюция', 'Darwin proposed the theory of evolution.', 6, $science],
            ['theory', 'ˈθɪəri', 'теория', 'Scientists tested the new theory.', 4, $science],
            ['experiment', 'ɪkˈsperɪmənt', 'эксперимент', 'We conducted an experiment in the lab.', 4, $science],
            ['laboratory', 'ləˈbɒrətri', 'лаборатория', 'The samples were sent to a laboratory.', 4, $science],
            ['microscope', 'ˈmaɪkrəskəʊp', 'микроскоп', 'She examined the sample under a microscope.', 5, $science],
            ['telescope', 'ˈtelɪskəʊp', 'телескоп', 'Astronomers use telescopes to study stars.', 5, $science],
            ['energy', 'ˈenədʒi', 'энергия', 'Solar panels convert sunlight into energy.', 3, $science],
            ['force', 'fɔːs', 'сила', 'Gravity is a force that pulls objects down.', 4, $science],
            ['mass', 'mæs', 'масса', 'The mass of the object was measured precisely.', 5, $science],
            ['velocity', 'vəˈlɒsɪti', 'скорость', 'The rocket reached a very high velocity.', 7, $science],
            ['acceleration', 'əkˌseləˈreɪʃən', 'ускорение', 'The car\'s acceleration was impressive.', 7, $science],
            ['friction', 'ˈfrɪkʃən', 'трение', 'Friction slows down moving objects.', 6, $science],
            ['electron', 'ɪˈlektrɒn', 'электрон', 'Electrons orbit the nucleus of an atom.', 7, $science],
            ['proton', 'ˈprəʊtɒn', 'протон', 'A proton has a positive electric charge.', 7, $science],
            ['neutron', 'ˈnjuːtrɒn', 'нейтрон', 'A neutron has no electric charge.', 7, $science],
            ['nucleus', 'ˈnjuːkliəs', 'ядро', 'Protons and neutrons are found in the nucleus.', 7, $science],
            ['element', 'ˈelɪmənt', 'элемент', 'Oxygen is a chemical element.', 5, $science],
            ['compound', 'ˈkɒmpaʊnd', 'соединение', 'Water is a compound of hydrogen and oxygen.', 6, $science],
            ['mixture', 'ˈmɪkstʃə', 'смесь', 'Air is a mixture of different gases.', 5, $science],
            ['reaction', 'riˈækʃən', 'реакция', 'The chemical reaction produced heat.', 5, $science],
            ['catalyst', 'ˈkætəlɪst', 'катализатор', 'Enzymes act as catalysts in the body.', 8, $science],
            ['acid', 'ˈæsɪd', 'кислота', 'Lemon juice contains citric acid.', 5, $science],
            ['base', 'beɪs', 'основание', 'Soap is a common example of a base.', 5, $science],
            ['volume', 'ˈvɒljuːm', 'объём', 'We measured the volume of the liquid.', 5, $science],
            ['density', 'ˈdensɪti', 'плотность', 'Gold has a very high density.', 6, $science],
            ['substance', 'ˈsʌbstəns', 'вещество', 'This substance is highly toxic.', 5, $science],
            ['particle', 'ˈpɑːtɪkl', 'частица', 'Dust particles float in the air.', 5, $science],
            ['wave', 'weɪv', 'волна', 'Light travels as a wave.', 4, $science],
            ['frequency', 'ˈfriːkwənsi', 'частота', 'The frequency of the sound was very high.', 6, $science],
            ['wavelength', 'ˈweɪvleŋθ', 'длина волны', 'Blue light has a shorter wavelength than red.', 7, $science],
            ['spectrum', 'ˈspektrəm', 'спектр', 'A rainbow shows the visible spectrum of light.', 7, $science],
            ['radiation', 'ˌreɪdiˈeɪʃən', 'излучение', 'The sun emits radiation.', 6, $science],
            ['magnetic', 'mægˈnetɪk', 'магнитный', 'The Earth has a magnetic field.', 5, $science],
            ['electric', 'ɪˈlektrɪk', 'электрический', 'The car runs on an electric motor.', 4, $science],
            ['current', 'ˈkʌrənt', 'ток', 'Electric current flows through the wire.', 5, $science],
            ['circuit', 'ˈsɜːkɪt', 'цепь', 'The circuit was broken, so the light stopped working.', 5, $science],
            ['voltage', 'ˈvəʊltɪdʒ', 'напряжение', 'Check the voltage before connecting the device.', 6, $science],
            ['resistance', 'rɪˈzɪstəns', 'сопротивление', 'The wire has low electrical resistance.', 6, $science],
            ['conductor', 'kənˈdʌktə', 'проводник', 'Copper is a good conductor of electricity.', 6, $science],
            ['insulator', 'ˈɪnsjuleɪtə', 'изолятор', 'Rubber is used as an insulator.', 7, $science],
            ['generator', 'ˈdʒenəreɪtə', 'генератор', 'The generator produces electricity for the village.', 5, $science],
            ['engine', 'ˈendʒɪn', 'двигатель', 'The car has a powerful engine.', 3, $science],
            ['mechanism', 'ˈmekənɪzəm', 'механизм', 'The clock has a complex mechanism inside.', 6, $science],
            ['invention', 'ɪnˈvenʃən', 'изобретение', 'The telephone was a groundbreaking invention.', 4, $science],
            ['discovery', 'dɪsˈkʌvəri', 'открытие', 'The discovery changed our understanding of the universe.', 4, $science],
            ['research', 'rɪˈsɜːtʃ', 'исследование', 'She is doing research on climate change.', 4, $science],
            ['researcher', 'rɪˈsɜːtʃə', 'исследователь', 'The researcher published her findings.', 5, $science],
            ['scientist', 'ˈsaɪəntɪst', 'учёный', 'The scientist won a Nobel Prize.', 3, $science],
            ['biologist', 'baɪˈɒlədʒɪst', 'биолог', 'A biologist studies living organisms.', 5, $science],
            ['chemist', 'ˈkemɪst', 'химик', 'The chemist mixed the two solutions carefully.', 5, $science],
            ['physicist', 'ˈfɪzɪsɪst', 'физик', 'Einstein was a famous physicist.', 5, $science],
            ['geologist', 'dʒiˈɒlədʒɪst', 'геолог', 'The geologist studied rock formations.', 6, $science],
            ['astronomer', 'əˈstrɒnəmə', 'астроном', 'The astronomer discovered a new star.', 5, $science],
            ['observation', 'ˌɒbzəˈveɪʃən', 'наблюдение', 'Careful observation is key to good science.', 5, $science],
            ['data', 'ˈdeɪtə', 'данные', 'The data shows a clear pattern.', 4, $science],
            ['measurement', 'ˈmeʒəmənt', 'измерение', 'Accurate measurement is essential in science.', 5, $science],
            ['calculation', 'ˌkælkjʊˈleɪʃən', 'вычисление', 'The calculation took several hours.', 5, $science],
            ['formula', 'ˈfɔːmjʊlə', 'формула', 'The formula for water is H2O.', 5, $science],
            ['equation', 'ɪˈkweɪʒən', 'уравнение', 'Solve this equation for x.', 5, $science],
            ['graph', 'ɡrɑːf', 'график', 'The graph shows the results clearly.', 4, $science],
            ['diagram', 'ˈdaɪəɡræm', 'диаграмма', 'The diagram explains how the engine works.', 4, $science],
            ['model', 'ˈmɒdəl', 'модель', 'Scientists built a model to test their theory.', 4, $science],
            ['simulation', 'ˌsɪmjʊˈleɪʃən', 'симуляция', 'The simulation predicted the weather accurately.', 6, $science],
            ['prediction', 'prɪˈdɪkʃən', 'предсказание', 'The prediction turned out to be correct.', 5, $science],
            ['proof', 'pruːf', 'доказательство', 'We need proof before we accept the theory.', 4, $science],
            ['fact', 'fækt', 'факт', 'It is a scientific fact that water boils at 100°C.', 3, $science],
            ['phenomenon', 'fɪˈnɒmɪnən', 'явление', 'Lightning is a natural phenomenon.', 6, $science],
            ['species', 'ˈspiːʃiːz', 'вид', 'This species is found only in the Amazon.', 5, $science],
            ['organism', 'ˈɔːɡənɪzəm', 'организм', 'Every living organism needs energy.', 5, $science],
            ['ecosystem', 'ˈiːkəʊsɪstəm', 'экосистема', 'The forest is a complex ecosystem.', 6, $science],
            ['environment', 'ɪnˈvaɪərənmənt', 'окружающая среда', 'We must protect the environment.', 4, $science],
            ['climate', 'ˈklaɪmət', 'климат', 'The climate is changing rapidly.', 4, $science],
            ['atmosphere', 'ˈætməsfɪə', 'атмосфера', 'The atmosphere protects us from radiation.', 5, $science],
            ['ozone', 'ˈəʊzəʊn', 'озон', 'The ozone layer absorbs harmful UV rays.', 6, $science],
            ['carbon', 'ˈkɑːbən', 'углерод', 'Carbon is found in all living things.', 5, $science],
            ['oxygen', 'ˈɒksɪdʒən', 'кислород', 'We need oxygen to breathe.', 4, $science],
            ['hydrogen', 'ˈhaɪdrədʒən', 'водород', 'Hydrogen is the lightest element.', 5, $science],
            ['nitrogen', 'ˈnaɪtrədʒən', 'азот', 'Nitrogen makes up most of the air we breathe.', 6, $science],
            ['methane', 'ˈmiːθeɪn', 'метан', 'Methane is a powerful greenhouse gas.', 7, $science],
            ['greenhouse', 'ˈɡriːnhaʊs', 'парниковый', 'Greenhouse gases trap heat in the atmosphere.', 5, $science],
            ['photosynthesis', 'ˌfəʊtəʊˈsɪnθəsɪs', 'фотосинтез', 'Plants make food through photosynthesis.', 7, $science],
            ['respiration', 'ˌrespəˈreɪʃən', 'дыхание', 'Cellular respiration produces energy.', 7, $science],
            ['metabolism', 'məˈtæbəlɪzəm', 'обмен веществ', 'Exercise can speed up your metabolism.', 6, $science],
            ['enzyme', 'ˈenzaɪm', 'фермент', 'Enzymes speed up chemical reactions in the body.', 7, $science],
            ['protein', 'ˈprəʊtiːn', 'белок', 'Meat and beans are good sources of protein.', 4, $science],
            ['bacteria', 'bækˈtɪəriə', 'бактерии', 'Some bacteria are helpful to humans.', 5, $science],
            ['virus', 'ˈvaɪərəs', 'вирус', 'The virus spread quickly through the population.', 4, $science],
            ['vaccine', 'ˈvæksiːn', 'вакцина', 'The vaccine protects against the disease.', 5, $science],
            ['antibody', 'ˈæntibɒdi', 'антитело', 'The body produces antibodies to fight infection.', 7, $science],
            ['immune', 'ɪˈmjuːn', 'иммунный', 'A healthy diet strengthens the immune system.', 5, $science],
            ['infection', 'ɪnˈfekʃən', 'инфекция', 'The wound became infected.', 4, $science],
            ['disease', 'dɪˈziːz', 'болезнь', 'The disease affects thousands of people every year.', 4, $science],
            ['symptom', 'ˈsɪmptəm', 'симптом', 'A fever is a common symptom of infection.', 4, $science],
            ['diagnosis', 'ˌdaɪəɡˈnəʊsɪs', 'диагноз', 'The doctor gave an accurate diagnosis.', 6, $science],
            ['treatment', 'ˈtriːtmənt', 'лечение', 'The treatment lasted several weeks.', 4, $science],
            ['therapy', 'ˈθerəpi', 'терапия', 'She started physical therapy after the accident.', 5, $science],
            ['surgery', 'ˈsɜːdʒəri', 'операция', 'He needs surgery to fix his knee.', 4, $science],
            ['anatomy', 'əˈnætəmi', 'анатомия', 'Medical students study human anatomy.', 6, $science],
            ['physiology', 'ˌfɪziˈɒlədʒi', 'физиология', 'Physiology explains how the body functions.', 7, $science],
            ['skeleton', 'ˈskelɪtən', 'скелет', 'The human skeleton has 206 bones.', 4, $science],
            ['muscle', 'ˈmʌsəl', 'мышца', 'Regular exercise strengthens your muscles.', 3, $science],
            ['tissue', 'ˈtɪʃuː', 'ткань', 'Muscle tissue can repair itself over time.', 5, $science],
            ['organ', 'ˈɔːɡən', 'орган', 'The heart is a vital organ.', 4, $science],
            ['nerve', 'nɜːv', 'нерв', 'The signal travels along the nerve.', 4, $science],
            ['brain', 'breɪn', 'мозг', 'The human brain is incredibly complex.', 3, $science],
            ['neuron', 'ˈnjʊərɒn', 'нейрон', 'Neurons send signals throughout the body.', 6, $science],
            ['hormone', 'ˈhɔːməʊn', 'гормон', 'Stress can affect hormone levels.', 5, $science],
            ['universe', 'ˈjuːnɪvɜːs', 'вселенная', 'The universe is constantly expanding.', 4, $science],
            ['galaxy', 'ˈɡæləksi', 'галактика', 'Our galaxy is called the Milky Way.', 4, $science],
            ['planet', 'ˈplænɪt', 'планета', 'Mars is the fourth planet from the sun.', 2, $science],
            ['star', 'stɑː', 'звезда', 'The sky was full of stars.', 2, $science],
            ['comet', 'ˈkɒmɪt', 'комета', 'The comet was visible for several nights.', 5, $science],
            ['asteroid', 'ˈæstərɔɪd', 'астероид', 'An asteroid could hit the Earth one day.', 5, $science],
            ['orbit', 'ˈɔːbɪt', 'орбита', 'The satellite is in orbit around the Earth.', 5, $science],
            ['satellite', 'ˈsætəlaɪt', 'спутник', 'The satellite sends signals back to Earth.', 4, $science],
            ['solar', 'ˈsəʊlə', 'солнечный', 'We use solar panels to generate power.', 4, $science],
            ['lunar', 'ˈluːnə', 'лунный', 'The lunar eclipse was visible last night.', 5, $science],
            ['eclipse', 'ɪˈklɪps', 'затмение', 'A solar eclipse is a rare event.', 5, $science],
            ['spacecraft', 'ˈspeɪskrɑːft', 'космический корабль', 'The spacecraft landed safely on the moon.', 5, $science],
            ['astronaut', 'ˈæstrənɔːt', 'космонавт', 'The astronaut spent six months in space.', 4, $science],
            ['rocket', 'ˈrɒkɪt', 'ракета', 'The rocket launched successfully into orbit.', 3, $science],
            ['launch', 'lɔːntʃ', 'запуск', 'The launch was delayed due to bad weather.', 4, $science],
            ['mission', 'ˈmɪʃən', 'миссия', 'The space mission lasted two years.', 4, $science],
            ['fossil', 'ˈfɒsəl', 'ископаемое', 'They found a dinosaur fossil in the desert.', 5, $science],
            ['extinct', 'ɪkˈstɪŋkt', 'вымерший', 'Dinosaurs became extinct millions of years ago.', 5, $science],
            ['adaptation', 'ˌædæpˈteɪʃən', 'адаптация', 'This adaptation helps the animal survive in the cold.', 6, $science],
            ['mutation', 'mjuːˈteɪʃən', 'мутация', 'A genetic mutation can cause disease.', 7, $science],
            ['cognitive', 'ˈkɒɡnɪtɪv', 'когнитивный', 'Cognitive skills improve with practice.', 7, $science],
            ['psychology', 'saɪˈkɒlədʒi', 'психология', 'She studies psychology at university.', 5, $science],
            ['sociology', 'ˌsəʊsiˈɒlədʒi', 'социология', 'Sociology examines how societies function.', 6, $science],
            ['statistics', 'stəˈtɪstɪks', 'статистика', 'The statistics show a clear trend.', 5, $science],
            ['probability', 'ˌprɒbəˈbɪləti', 'вероятность', 'The probability of rain today is high.', 6, $science],
            ['constant', 'ˈkɒnstənt', 'постоянная', 'The speed of light is a physical constant.', 5, $science],
            ['magnet', 'ˈmæɡnɪt', 'магнит', 'The magnet attracted the metal pins.', 3, $science],
            ['thermometer', 'θəˈmɒmɪtə', 'термометр', 'Use a thermometer to check the temperature.', 4, $science],
            ['barometer', 'bəˈrɒmɪtə', 'барометр', 'The barometer predicted a storm.', 6, $science],
            ['chemical', 'ˈkemɪkəl', 'химический', 'The factory produces various chemical products.', 4, $science],
            ['biology', 'baɪˈɒlədʒi', 'биология', 'Biology is the study of living things.', 3, $science],
            ['physics', 'ˈfɪzɪks', 'физика', 'She enjoys studying physics and mathematics.', 3, $science],
            ['geology', 'dʒiˈɒlədʒi', 'геология', 'Geology explains the structure of the Earth.', 5, $science],
            ['botany', 'ˈbɒtəni', 'ботаника', 'Botany is the scientific study of plants.', 6, $science],
            ['zoology', 'zuːˈɒlədʒi', 'зоология', 'Zoology focuses on the study of animals.', 6, $science],
            ['meteorology', 'ˌmiːtiəˈrɒlədʒi', 'метеорология', 'Meteorology helps us predict the weather.', 7, $science],

            // ===== Компьютеры и интернет (Computers and Internet) =====
            ['algorithm', 'ˈælɡərɪðəm', 'алгоритм', 'The algorithm sorts the numbers quickly.', 6, $tech],
            ['software', 'ˈsɒftweə', 'программное обеспечение', 'This software helps you edit photos.', 3, $tech],
            ['hardware', 'ˈhɑːdweə', 'аппаратное обеспечение', 'The computer\'s hardware needs an upgrade.', 3, $tech],
            ['application', 'ˌæplɪˈkeɪʃən', 'приложение', 'I downloaded a new application for my phone.', 3, $tech],
            ['browser', 'ˈbraʊzə', 'браузер', 'Open your browser and search for the site.', 2, $tech],
            ['website', 'ˈwebsaɪt', 'сайт', 'The company launched a new website.', 2, $tech],
            ['server', 'ˈsɜːvə', 'сервер', 'The server crashed during peak hours.', 4, $tech],
            ['database', 'ˈdeɪtəbeɪs', 'база данных', 'All the information is stored in a database.', 4, $tech],
            ['network', 'ˈnetwɜːk', 'сеть', 'Connect your laptop to the network.', 3, $tech],
            ['router', 'ˈruːtə', 'роутер', 'The router provides Wi-Fi for the whole house.', 3, $tech],
            ['wifi', 'ˈwaɪfaɪ', 'вай-фай', 'Is there free wifi in this café?', 1, $tech],
            ['bluetooth', 'ˈbluːtuːθ', 'блютус', 'Connect your headphones via bluetooth.', 2, $tech],
            ['keyboard', 'ˈkiːbɔːd', 'клавиатура', 'She typed quickly on the keyboard.', 2, $tech],
            ['monitor', 'ˈmɒnɪtə', 'монитор', 'The monitor displays a sharp, clear image.', 2, $tech],
            ['cursor', 'ˈkɜːsə', 'курсор', 'Move the cursor to the top of the screen.', 3, $tech],
            ['folder', 'ˈfəʊldə', 'папка', 'Save the file in the correct folder.', 2, $tech],
            ['file', 'faɪl', 'файл', 'I accidentally deleted the file.', 2, $tech],
            ['spreadsheet', 'ˈspredʃiːt', 'таблица', 'She created a spreadsheet to track expenses.', 4, $tech],
            ['presentation', 'ˌprezənˈteɪʃən', 'презентация', 'He prepared a presentation for the meeting.', 3, $tech],
            ['email', 'ˈiːmeɪl', 'электронная почта', 'Please send me an email with the details.', 2, $tech],
            ['attachment', 'əˈtætʃmənt', 'вложение', 'I forgot to add the attachment to the email.', 4, $tech],
            ['inbox', 'ˈɪnbɒks', 'входящие', 'My inbox is full of unread messages.', 3, $tech],
            ['spam', 'spæm', 'спам', 'The filter blocks most spam emails.', 2, $tech],
            ['firewall', 'ˈfaɪəwɔːl', 'файрвол', 'The firewall blocked the suspicious connection.', 5, $tech],
            ['antivirus', 'ˌæntiˈvaɪərəs', 'антивирус', 'Install antivirus software to protect your computer.', 4, $tech],
            ['encryption', 'ɪnˈkrɪpʃən', 'шифрование', 'Encryption keeps your data safe from hackers.', 6, $tech],
            ['cybersecurity', 'ˌsaɪbəsɪˈkjʊərəti', 'кибербезопасность', 'The company invested heavily in cybersecurity.', 6, $tech],
            ['hacker', 'ˈhækə', 'хакер', 'A hacker tried to break into the system.', 4, $tech],
            ['username', 'ˈjuːzəneɪm', 'имя пользователя', 'Enter your username and password to log in.', 2, $tech],
            ['login', 'ˈlɒɡɪn', 'вход', 'I forgot my login details.', 2, $tech],
            ['logout', 'ˈlɒɡaʊt', 'выход', 'Remember to logout after using a public computer.', 2, $tech],
            ['upload', 'ʌpˈləʊd', 'загрузить (на сервер)', 'Upload the photos to the shared folder.', 3, $tech],
            ['storage', 'ˈstɔːrɪdʒ', 'хранилище', 'Cloud storage lets you access files anywhere.', 4, $tech],
            ['memory', 'ˈmeməri', 'память', 'This laptop has 16 gigabytes of memory.', 3, $tech],
            ['processor', 'ˈprəʊsesə', 'процессор', 'The new processor makes the computer much faster.', 4, $tech],
            ['chip', 'tʃɪp', 'чип', 'This tiny chip controls the whole device.', 3, $tech],
            ['motherboard', 'ˈmʌðəbɔːd', 'материнская плата', 'The motherboard connects all the computer parts.', 5, $tech],
            ['graphics', 'ˈɡræfɪks', 'графика', 'The game has stunning graphics.', 3, $tech],
            ['resolution', 'ˌrezəˈluːʃən', 'разрешение', 'This screen has a very high resolution.', 4, $tech],
            ['pixel', 'ˈpɪksəl', 'пиксель', 'Each pixel represents a tiny dot of colour.', 4, $tech],
            ['bandwidth', 'ˈbændwɪdθ', 'пропускная способность', 'Streaming video requires a lot of bandwidth.', 6, $tech],
            ['wireless', 'ˈwaɪələs', 'беспроводной', 'We bought wireless headphones.', 3, $tech],
            ['cable', 'ˈkeɪbəl', 'кабель', 'Plug the cable into the correct port.', 2, $tech],
            ['USB', 'ˌjuː.esˈbiː', 'usb', 'Save the file to the USB drive.', 2, $tech],
            ['charger', 'ˈtʃɑːdʒə', 'зарядное устройство', 'I forgot my phone charger at home.', 2, $tech],
            ['touchscreen', 'ˈtʌtʃskriːn', 'сенсорный экран', 'The tablet has a large touchscreen.', 3, $tech],
            ['smartphone', 'ˈsmɑːtfəʊn', 'смартфон', 'Almost everyone has a smartphone these days.', 2, $tech],
            ['tablet', 'ˈtæblɪt', 'планшет', 'She reads books on her tablet.', 2, $tech],
            ['desktop', 'ˈdesktɒp', 'настольный компьютер', 'He prefers a desktop computer for gaming.', 3, $tech],
            ['operating system', 'ˈɒpəreɪtɪŋ ˈsɪstəm', 'операционная система', 'Which operating system does your laptop use?', 5, $tech],
            ['interface', 'ˈɪntəfeɪs', 'интерфейс', 'The app has a simple, clean interface.', 5, $tech],
            ['icon', 'ˈaɪkɒn', 'значок', 'Click the icon to open the app.', 3, $tech],
            ['toolbar', 'ˈtuːlbɑː', 'панель инструментов', 'The toolbar contains all the editing options.', 4, $tech],
            ['bookmark', 'ˈbʊkmɑːk', 'закладка', 'I saved the article as a bookmark.', 3, $tech],
            ['search engine', 'sɜːtʃ ˈendʒɪn', 'поисковая система', 'She used a search engine to find the answer.', 3, $tech],
            ['hyperlink', 'ˈhaɪpəlɪŋk', 'гиперссылка', 'Click the hyperlink to go to the page.', 4, $tech],
            ['url', 'ˌjuːˌɑːˈel', 'url-адрес', 'Type the URL into the address bar.', 3, $tech],
            ['domain', 'dəʊˈmeɪn', 'домен', 'We registered a new domain for the website.', 4, $tech],
            ['hosting', 'ˈhəʊstɪŋ', 'хостинг', 'The website hosting costs $10 a month.', 5, $tech],
            ['streaming', 'ˈstriːmɪŋ', 'стриминг', 'Streaming services are very popular now.', 3, $tech],
            ['buffering', 'ˈbʌfərɪŋ', 'буферизация', 'The video kept buffering because of slow internet.', 5, $tech],
            ['notification', 'ˌnəʊtɪfɪˈkeɪʃən', 'уведомление', 'I got a notification about a new message.', 4, $tech],
            ['uninstall', 'ˌʌnɪnˈstɔːl', 'удалить (программу)', 'You can uninstall apps you no longer use.', 4, $tech],
            ['reboot', 'riːˈbuːt', 'перезагрузка', 'Try to reboot the computer if it freezes.', 4, $tech],
            ['bug', 'bʌɡ', 'ошибка (в коде)', 'The developers fixed the bug in the update.', 3, $tech],
            ['debug', 'diːˈbʌɡ', 'отладить', 'It took hours to debug the programme.', 5, $tech],
            ['code', 'kəʊd', 'код', 'She writes code for a living.', 3, $tech],
            ['coding', 'ˈkəʊdɪŋ', 'программирование', 'He is learning coding in his free time.', 3, $tech],
            ['programmer', 'ˈprəʊɡræmə', 'программист', 'The programmer fixed the error quickly.', 3, $tech],
            ['developer', 'dɪˈveləpə', 'разработчик', 'Our team includes five developers.', 4, $tech],
            ['programming language', 'ˈprəʊɡræmɪŋ ˈlæŋɡwɪdʒ', 'язык программирования', 'Python is a popular programming language.', 5, $tech],
            ['syntax', 'ˈsɪntæks', 'синтаксис', 'There is a syntax error in the code.', 6, $tech],
            ['array', 'əˈreɪ', 'массив', 'The array stores multiple values.', 6, $tech],
            ['loop', 'luːp', 'цикл', 'The programme runs in a continuous loop.', 5, $tech],
            ['compiler', 'kəmˈpaɪlə', 'компилятор', 'The compiler found an error in the code.', 7, $tech],
            ['framework', 'ˈfreɪmwɜːk', 'фреймворк', 'This framework makes development much faster.', 6, $tech],
            ['repository', 'rɪˈpɒzɪtəri', 'репозиторий', 'The code is stored in an online repository.', 6, $tech],
            ['version', 'ˈvɜːʒən', 'версия', 'Update to the latest version of the app.', 3, $tech],
            ['robot', 'ˈrəʊbɒt', 'робот', 'The factory uses robots to assemble cars.', 3, $tech],
            ['automation', 'ˌɔːtəˈmeɪʃən', 'автоматизация', 'Automation has changed the way factories work.', 6, $tech],
            ['chatbot', 'ˈtʃætbɒt', 'чат-бот', 'The website uses a chatbot to answer questions.', 4, $tech],
            ['avatar', 'ˈævətɑː', 'аватар', 'She chose a cartoon avatar for her profile.', 3, $tech],
            ['emoji', 'ɪˈməʊdʒi', 'эмодзи', 'She sent a message full of emojis.', 2, $tech],
            ['hashtag', 'ˈhæʃtæɡ', 'хэштег', 'Add a hashtag to make your post easier to find.', 3, $tech],
            ['blog', 'blɒɡ', 'блог', 'He writes a blog about travelling.', 2, $tech],
            ['vlog', 'vlɒɡ', 'влог', 'She started a vlog about her daily life.', 3, $tech],
            ['podcast', 'ˈpɒdkɑːst', 'подкаст', 'I listen to a podcast every morning.', 3, $tech],
            ['subscriber', 'səbˈskraɪbə', 'подписчик', 'The channel has over a million subscribers.', 4, $tech],
            ['follower', 'ˈfɒləʊə', 'подписчик', 'She has thousands of followers on social media.', 3, $tech],
            ['comment', 'ˈkɒment', 'комментарий', 'He left a kind comment on my post.', 3, $tech],
            ['post', 'pəʊst', 'публикация', 'She shared a new post about her trip.', 2, $tech],
            ['feed', 'fiːd', 'лента новостей', 'I scrolled through my feed for an hour.', 3, $tech],
            ['profile', 'ˈprəʊfaɪl', 'профиль', 'Update your profile with a new photo.', 3, $tech],
            ['account', 'əˈkaʊnt', 'аккаунт', 'I created a new account on the platform.', 3, $tech],
            ['privacy', 'ˈprɪvəsi', 'конфиденциальность', 'Check your privacy settings regularly.', 4, $tech],
            ['settings', 'ˈsetɪŋz', 'настройки', 'You can change the language in the settings.', 3, $tech],
            ['permission', 'pəˈmɪʃən', 'разрешение (доступа)', 'The app asked for permission to use the camera.', 4, $tech],
            ['access', 'ˈækses', 'доступ', 'Only employees have access to this system.', 4, $tech],
            ['authentication', 'ɔːˌθentɪˈkeɪʃən', 'аутентификация', 'Two-factor authentication improves security.', 7, $tech],
            ['fingerprint', 'ˈfɪŋɡəprɪnt', 'отпечаток пальца', 'Unlock your phone with a fingerprint.', 4, $tech],
            ['virtual reality', 'ˈvɜːtʃuəl riˈæləti', 'виртуальная реальность', 'Virtual reality games feel incredibly realistic.', 5, $tech],
            ['augmented reality', 'ɔːɡˈmentɪd riˈæləti', 'дополненная реальность', 'The app uses augmented reality to place furniture in your room.', 6, $tech],
            ['gigabyte', 'ˈɡɪɡəbaɪt', 'гигабайт', 'This file is over two gigabytes.', 4, $tech],
            ['megabyte', 'ˈmeɡəbaɪt', 'мегабайт', 'The photo is about five megabytes.', 4, $tech],
            ['terabyte', 'ˈterəbaɪt', 'терабайт', 'The hard drive can store one terabyte of data.', 5, $tech],
            ['signal', 'ˈsɪɡnəl', 'сигнал', 'The phone signal is weak in this area.', 3, $tech],
        ];
    }
}
