<?php

namespace Database\Seeders;

use App\Models\Vocabulary\Word;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Third batch of the vocabulary expansion (see VocabularyBatch1Seeder).
 * Skips any English word that already exists in the words table
 * (case-insensitive) so the seeder is safe to re-run.
 */
class VocabularyBatch3Seeder extends Seeder
{
    public function run(): void
    {
        $existing = Word::pluck('word')->map(fn ($w) => Str::lower($w))->flip();

        $created = 0;
        $skipped = 0;

        foreach ($this->entries() as $row) {
            [$en, $ipa, $ru, $example, $difficulty, $category] = $row;

            if (isset($existing[Str::lower($en)])) {
                $skipped++;

                continue;
            }

            $word = Word::create([
                'word' => $en,
                'transcription' => $ipa,
                'example' => $example,
                'difficulty' => $difficulty,
                'category' => $category,
            ]);

            $word->translations()->create([
                'language' => 'ru',
                'translation' => $ru,
                'example' => $example,
            ]);

            $existing[Str::lower($en)] = true;
            $created++;
        }

        $this->command?->info("VocabularyBatch3Seeder: +{$created} words, {$skipped} skipped as already existing.");
    }

    /**
     * @return array<int, array{0: string, 1: string, 2: string, 3: string, 4: int, 5: string}>
     */
    private function entries(): array
    {
        $pol = 'Политика и государство';
        $art = 'Искусство и живопись';

        return [
            // ===== Политика и государство (Politics and Government) =====
            ['government', 'ˈɡʌvənmənt', 'правительство', 'The government announced new policies today.', 2, $pol],
            ['parliament', 'ˈpɑːləmənt', 'парламент', 'Parliament passed the new law.', 3, $pol],
            ['president', 'ˈprezɪdənt', 'президент', 'The president gave a speech last night.', 2, $pol],
            ['prime minister', 'praɪm ˈmɪnɪstə', 'премьер-министр', 'The prime minister met with foreign leaders.', 3, $pol],
            ['minister', 'ˈmɪnɪstə', 'министр', 'The foreign minister visited China.', 3, $pol],
            ['senator', 'ˈsenətə', 'сенатор', 'The senator proposed a new bill.', 4, $pol],
            ['congress', 'ˈkɒŋɡres', 'конгресс', 'Congress approved the budget.', 3, $pol],
            ['election', 'ɪˈlekʃən', 'выборы', 'The presidential election is next month.', 3, $pol],
            ['vote', 'vəʊt', 'голос(овать)', 'Everyone has the right to vote.', 2, $pol],
            ['voter', 'ˈvəʊtə', 'избиратель', 'Millions of voters went to the polls.', 3, $pol],
            ['ballot', 'ˈbælət', 'бюллетень', 'She marked her choice on the ballot.', 4, $pol],
            ['candidate', 'ˈkændɪdət', 'кандидат', 'Three candidates are running for mayor.', 3, $pol],
            ['democracy', 'dɪˈmɒkrəsi', 'демократия', 'The country became a democracy in 1990.', 4, $pol],
            ['republic', 'rɪˈpʌblɪk', 'республика', 'France is a republic.', 4, $pol],
            ['monarchy', 'ˈmɒnəki', 'монархия', 'The UK is a constitutional monarchy.', 4, $pol],
            ['dictatorship', 'dɪkˈteɪtəʃɪp', 'диктатура', 'The country suffered under a dictatorship.', 5, $pol],
            ['constitution', 'ˌkɒnstɪˈtjuːʃən', 'конституция', 'The constitution guarantees basic rights.', 4, $pol],
            ['law', 'lɔː', 'закон', 'This law protects consumers.', 1, $pol],
            ['legislation', 'ˌledʒɪsˈleɪʃən', 'законодательство', 'New legislation will affect small businesses.', 5, $pol],
            ['amendment', 'əˈmendmənt', 'поправка', 'The amendment was approved by parliament.', 5, $pol],
            ['veto', 'ˈviːtəʊ', 'вето', 'The president used his veto power.', 5, $pol],
            ['referendum', 'ˌrefəˈrendəm', 'референдум', 'A referendum will decide the issue.', 5, $pol],
            ['citizen', 'ˈsɪtɪzən', 'гражданин', 'Every citizen has the right to vote.', 3, $pol],
            ['citizenship', 'ˈsɪtɪzənʃɪp', 'гражданство', 'She applied for citizenship last year.', 4, $pol],
            ['nation', 'ˈneɪʃən', 'нация', 'The whole nation watched the ceremony.', 2, $pol],
            ['sovereignty', 'ˈsɒvrənti', 'суверенитет', 'The country values its national sovereignty.', 6, $pol],
            ['diplomacy', 'dɪˈpləʊməsi', 'дипломатия', 'The conflict was resolved through diplomacy.', 5, $pol],
            ['embassy', 'ˈembəsi', 'посольство', 'She works at the British embassy.', 3, $pol],
            ['ambassador', 'æmˈbæsədə', 'посол', 'The ambassador met with local officials.', 4, $pol],
            ['treaty', 'ˈtriːti', 'договор (международный)', 'The two countries signed a peace treaty.', 4, $pol],
            ['alliance', 'əˈlaɪəns', 'союз (политический)', 'The two nations formed a military alliance.', 4, $pol],
            ['coalition', 'ˌkəʊəˈlɪʃən', 'коалиция', 'A coalition government was formed after the election.', 5, $pol],
            ['opposition', 'ˌɒpəˈzɪʃən', 'оппозиция', 'The opposition criticised the new policy.', 4, $pol],
            ['majority', 'məˈdʒɒrəti', 'большинство', 'The party won a majority of seats.', 4, $pol],
            ['minority', 'maɪˈnɒrəti', 'меньшинство', 'The minority party opposed the bill.', 4, $pol],
            ['debate', 'dɪˈbeɪt', 'дебаты', 'The candidates took part in a televised debate.', 3, $pol],
            ['reform', 'rɪˈfɔːm', 'реформа', 'The government promised economic reform.', 4, $pol],
            ['corruption', 'kəˈrʌpʃən', 'коррупция', 'The scandal exposed widespread corruption.', 5, $pol],
            ['bribery', 'ˈbraɪbəri', 'взяточничество', 'He was arrested for bribery.', 5, $pol],
            ['protest', 'ˈprəʊtest', 'протест', 'Thousands joined the protest downtown.', 3, $pol],
            ['demonstration', 'ˌdemənˈstreɪʃən', 'демонстрация', 'The demonstration remained peaceful.', 4, $pol],
            ['activist', 'ˈæktɪvɪst', 'активист', 'She is a well-known human rights activist.', 4, $pol],
            ['rebellion', 'rɪˈbeljən', 'восстание', 'The rebellion was crushed by the army.', 5, $pol],
            ['revolution', 'ˌrevəˈluːʃən', 'революция', 'The revolution changed the country forever.', 4, $pol],
            ['coup', 'kuː', 'государственный переворот', 'The military staged a coup last night.', 6, $pol],
            ['regime', 'reɪˈʒiːm', 'режим (политический)', 'The old regime finally collapsed.', 5, $pol],
            ['authoritarian', 'ɔːˌθɒrɪˈteəriən', 'авторитарный', 'The country is ruled by an authoritarian government.', 6, $pol],
            ['democratic', 'ˌdeməˈkrætɪk', 'демократический', 'They held free and democratic elections.', 4, $pol],
            ['liberal', 'ˈlɪbərəl', 'либеральный', 'The party has liberal views on social issues.', 4, $pol],
            ['conservative', 'kənˈsɜːvətɪv', 'консервативный', 'He holds fairly conservative political views.', 4, $pol],
            ['socialist', 'ˈsəʊʃəlɪst', 'социалистический', 'The socialist party won the election.', 5, $pol],
            ['communist', 'ˈkɒmjʊnɪst', 'коммунистический', 'The country was communist for decades.', 5, $pol],
            ['capitalism', 'ˈkæpɪtəlɪzəm', 'капитализм', 'Capitalism relies on free markets.', 5, $pol],
            ['socialism', 'ˈsəʊʃəlɪzəm', 'социализм', 'They debated the benefits of socialism.', 5, $pol],
            ['communism', 'ˈkɒmjʊnɪzəm', 'коммунизм', 'Communism collapsed in the region in 1991.', 5, $pol],
            ['ideology', 'ˌaɪdiˈɒlədʒi', 'идеология', 'The two parties have very different ideologies.', 6, $pol],
            ['propaganda', 'ˌprɒpəˈɡændə', 'пропаганда', 'The regime used propaganda to control the media.', 5, $pol],
            ['censorship', 'ˈsensəʃɪp', 'цензура', 'The country is criticised for its censorship.', 5, $pol],
            ['justice', 'ˈdʒʌstɪs', 'правосудие', 'The victims are still seeking justice.', 3, $pol],
            ['judiciary', 'dʒuːˈdɪʃəri', 'судебная власть', 'The judiciary must remain independent.', 7, $pol],
            ['court', 'kɔːt', 'суд', 'The case went to court.', 2, $pol],
            ['judge', 'dʒʌdʒ', 'судья', 'The judge sentenced him to five years.', 2, $pol],
            ['verdict', 'ˈvɜːdɪkt', 'вердикт', 'The jury delivered a guilty verdict.', 5, $pol],
            ['lawsuit', 'ˈlɔːsuːt', 'судебный иск', 'The company faces a lawsuit over the accident.', 5, $pol],
            ['plaintiff', 'ˈpleɪntɪf', 'истец', 'The plaintiff demanded compensation.', 6, $pol],
            ['defendant', 'dɪˈfendənt', 'ответчик/подсудимый', 'The defendant pleaded not guilty.', 6, $pol],
            ['jury', 'ˈdʒʊəri', 'присяжные', 'The jury reached a unanimous decision.', 4, $pol],
            ['witness', 'ˈwɪtnəs', 'свидетель', 'The witness described what she saw.', 3, $pol],
            ['testimony', 'ˈtestɪməni', 'показания', 'His testimony helped convict the criminal.', 5, $pol],
            ['prosecution', 'ˌprɒsɪˈkjuːʃən', 'обвинение (сторона)', 'The prosecution presented strong evidence.', 6, $pol],
            ['defense', 'dɪˈfens', 'защита (юридическая)', 'The defense argued he was innocent.', 5, $pol],
            ['appeal', 'əˈpiːl', 'апелляция', 'His lawyers filed an appeal.', 4, $pol],
            ['governor', 'ˈɡʌvənə', 'губернатор', 'The governor signed the new law.', 3, $pol],
            ['mayor', 'meə', 'мэр', 'The mayor opened the new hospital.', 3, $pol],
            ['council', 'ˈkaʊnsəl', 'совет (муниципальный)', 'The city council approved the budget.', 3, $pol],
            ['councillor', 'ˈkaʊnsələ', 'член совета', 'She was elected as a local councillor.', 4, $pol],
            ['municipality', 'mjuːˌnɪsɪˈpæləti', 'муниципалитет', 'The municipality manages local services.', 6, $pol],
            ['federal', 'ˈfedərəl', 'федеральный', 'Federal law overrides state law in this case.', 4, $pol],
            ['province', 'ˈprɒvɪns', 'провинция', 'The province has its own local government.', 4, $pol],
            ['territory', 'ˈterɪtəri', 'территория', 'The territory was disputed for decades.', 4, $pol],
            ['border', 'ˈbɔːdə', 'граница', 'They crossed the border without a passport.', 2, $pol],
            ['immigration', 'ˌɪmɪˈɡreɪʃən', 'иммиграция', 'Immigration policy is a hot political topic.', 5, $pol],
            ['emigration', 'ˌemɪˈɡreɪʃən', 'эмиграция', 'Emigration increased during the crisis.', 5, $pol],
            ['refugee', 'ˌrefjʊˈdʒiː', 'беженец', 'The refugees were given temporary shelter.', 4, $pol],
            ['asylum', 'əˈsaɪləm', 'убежище (политическое)', 'She was granted political asylum.', 6, $pol],
            ['visa', 'ˈviːzə', 'виза', 'You need a visa to enter the country.', 3, $pol],
            ['martial law', 'ˈmɑːʃəl lɔː', 'военное положение', 'Martial law was declared after the coup.', 6, $pol],
            ['civil war', 'ˈsɪvəl wɔː', 'гражданская война', 'The civil war lasted for five years.', 4, $pol],
            ['sanctions', 'ˈsæŋkʃənz', 'санкции', 'The UN imposed sanctions on the country.', 5, $pol],
            ['embargo', 'ɪmˈbɑːɡəʊ', 'эмбарго', 'The trade embargo damaged the economy.', 6, $pol],
            ['head of state', 'hed əv steɪt', 'глава государства', 'The queen was the head of state.', 5, $pol],
            ['cabinet', 'ˈkæbɪnət', 'кабинет министров', 'The prime minister reshuffled his cabinet.', 5, $pol],
            ['parliamentary', 'ˌpɑːləˈmentəri', 'парламентский', 'This is a parliamentary democracy.', 5, $pol],
            ['electorate', 'ɪˈlektərət', 'электорат', 'The electorate rejected the proposal.', 6, $pol],
            ['constituency', 'kənˈstɪtjʊənsi', 'избирательный округ', 'He represents a large rural constituency.', 6, $pol],
            ['ballot box', 'ˈbælət bɒks', 'урна для голосования', 'Voters lined up at the ballot box.', 4, $pol],
            ['poll', 'pəʊl', 'опрос (общественного мнения)', 'A recent poll shows rising support.', 3, $pol],
            ['polling station', 'ˈpəʊlɪŋ ˈsteɪʃən', 'избирательный участок', 'Long queues formed at the polling station.', 4, $pol],
            ['landslide', 'ˈlændslaɪd', 'убедительная победа', 'She won the election in a landslide.', 6, $pol],
            ['incumbent', 'ɪnˈkʌmbənt', 'действующий (о должности)', 'The incumbent president lost the election.', 7, $pol],
            ['impeachment', 'ɪmˈpiːtʃmənt', 'импичмент', 'Congress began impeachment proceedings.', 7, $pol],
            ['filibuster', 'ˈfɪlɪbʌstə', 'обструкция (парламентская)', 'The senator used a filibuster to delay the vote.', 7, $pol],
            ['lobbying', 'ˈlɒbiɪŋ', 'лоббирование', 'The industry spent millions on lobbying.', 6, $pol],
            ['lobbyist', 'ˈlɒbiɪst', 'лоббист', 'He works as a lobbyist in Washington.', 6, $pol],
            ['grassroots', 'ˈɡrɑːsruːts', 'низовой (о движении)', 'The campaign began as a grassroots movement.', 6, $pol],
            ['manifesto', 'ˌmænɪˈfestəʊ', 'манифест (партийный)', 'The party published its election manifesto.', 6, $pol],
            ['campaign trail', 'kæmˈpeɪn treɪl', 'предвыборная кампания (турне)', 'The candidate spent months on the campaign trail.', 6, $pol],
            ['swing state', 'swɪŋ steɪt', 'колеблющийся штат', 'The election will be decided in a few swing states.', 6, $pol],
            ['exit poll', 'ˈeksɪt pəʊl', 'опрос на выходе с участка', 'Exit polls predicted a close result.', 6, $pol],
            ['autocracy', 'ɔːˈtɒkrəsi', 'автократия', 'The country slid into autocracy.', 7, $pol],
            ['oligarchy', 'ˈɒlɪɡɑːki', 'олигархия', 'Critics say the country is really an oligarchy.', 7, $pol],
            ['theocracy', 'θiˈɒkrəsi', 'теократия', 'The state was ruled as a theocracy.', 7, $pol],
            ['secular', 'ˈsekjʊlə', 'светский', 'The country has a secular constitution.', 5, $pol],
            ['patriot', 'ˈpeɪtriət', 'патриот', 'He considers himself a true patriot.', 4, $pol],
            ['patriotism', 'ˈpeɪtriətɪzəm', 'патриотизм', 'The song is a symbol of national patriotism.', 5, $pol],
            ['nationalism', 'ˈnæʃənəlɪzəm', 'национализм', 'Nationalism has been rising across Europe.', 5, $pol],
            ['globalism', 'ˈɡləʊbəlɪzəm', 'глобализм', 'Some politicians criticise globalism.', 6, $pol],
            ['self-determination', 'ˌself dɪˌtɜːmɪˈneɪʃən', 'самоопределение', 'The region demanded the right to self-determination.', 7, $pol],
            ['annexation', 'ˌænekˈseɪʃən', 'аннексия', 'The annexation was condemned internationally.', 7, $pol],
            ['occupation', 'ˌɒkjʊˈpeɪʃən', 'оккупация', 'The occupation lasted for several years.', 5, $pol],
            ['ceasefire', 'ˈsiːsfaɪə', 'прекращение огня', 'Both sides agreed to a ceasefire.', 5, $pol],
            ['armistice', 'ˈɑːmɪstɪs', 'перемирие', 'The armistice ended the fighting.', 6, $pol],
            ['peacekeeping', 'ˈpiːskiːpɪŋ', 'миротворческий', 'UN peacekeeping troops were sent to the region.', 6, $pol],
            ['humanitarian', 'hjuːˌmænɪˈteəriən', 'гуманитарный', 'They provided humanitarian aid to refugees.', 5, $pol],
            ['NGO', 'ˌen dʒiː ˈəʊ', 'неправительственная организация', 'The NGO helps children in poverty.', 5, $pol],
            ['summit', 'ˈsʌmɪt', 'саммит', 'World leaders met at the climate summit.', 4, $pol],
            ['bilateral', 'baɪˈlætərəl', 'двусторонний', 'They signed a bilateral trade agreement.', 6, $pol],
            ['multilateral', 'ˌmʌltiˈlætərəl', 'многосторонний', 'The treaty is a multilateral agreement.', 7, $pol],
            ['unilateral', 'ˌjuːnɪˈlætərəl', 'односторонний', 'The country took unilateral action.', 6, $pol],
            ['term', 'tɜːm', 'срок (полномочий)', 'The president is serving his second term.', 3, $pol],

            // ===== Искусство и живопись (Art and Painting) =====
            ['painter', 'ˈpeɪntə', 'художник', 'She is a talented painter.', 2, $art],
            ['canvas', 'ˈkænvəs', 'холст', 'The artist stretched a new canvas.', 4, $art],
            ['easel', 'ˈiːzəl', 'мольберт', 'He set up his easel by the window.', 5, $art],
            ['palette', 'ˈpælət', 'палитра', 'She mixed colours on her palette.', 4, $art],
            ['sketch', 'sketʃ', 'набросок', 'He made a quick sketch of the building.', 3, $art],
            ['drawing', 'ˈdrɔːɪŋ', 'рисунок', 'The child showed her drawing to the class.', 2, $art],
            ['portrait', 'ˈpɔːtrət', 'портрет', 'The museum has a famous portrait of the king.', 4, $art],
            ['landscape', 'ˈlændskeɪp', 'пейзаж', 'She painted a beautiful landscape.', 4, $art],
            ['still life', 'stɪl laɪf', 'натюрморт', 'He painted a still life of fruit and flowers.', 5, $art],
            ['abstract', 'ˈæbstrækt', 'абстрактный', 'The gallery is showing abstract art.', 5, $art],
            ['sculpture', 'ˈskʌlptʃə', 'скульптура', 'The park has several bronze sculptures.', 4, $art],
            ['sculptor', 'ˈskʌlptə', 'скульптор', 'The sculptor carved the statue from marble.', 4, $art],
            ['statue', 'ˈstætʃuː', 'статуя', 'Tourists photograph the famous statue.', 3, $art],
            ['gallery', 'ˈɡæləri', 'галерея', 'We visited an art gallery yesterday.', 3, $art],
            ['exhibition', 'ˌeksɪˈbɪʃən', 'выставка', 'The exhibition attracted thousands of visitors.', 4, $art],
            ['masterpiece', 'ˈmɑːstəpiːs', 'шедевр', 'The painting is considered a masterpiece.', 4, $art],
            ['artwork', 'ˈɑːtwɜːk', 'произведение искусства', 'The artwork sold for millions.', 3, $art],
            ['mural', 'ˈmjʊərəl', 'настенная роспись', 'The mural covers the entire wall.', 5, $art],
            ['fresco', 'ˈfreskəʊ', 'фреска', 'The ceiling fresco took years to complete.', 6, $art],
            ['watercolour', 'ˈwɔːtəkʌlə', 'акварель', 'She prefers watercolour to oil paint.', 4, $art],
            ['acrylic', 'əˈkrɪlɪk', 'акрил', 'He painted the mural using acrylic paint.', 5, $art],
            ['charcoal', 'ˈtʃɑːkəʊl', 'уголь (для рисования)', 'She drew the portrait in charcoal.', 5, $art],
            ['pastel', 'ˈpæstəl', 'пастель', 'The artist used soft pastel colours.', 4, $art],
            ['ink', 'ɪŋk', 'чернила', 'He signed the drawing in black ink.', 2, $art],
            ['silhouette', 'ˌsɪluˈet', 'силуэт', 'You could see her silhouette against the light.', 5, $art],
            ['perspective', 'pəˈspektɪv', 'перспектива (в рисунке)', 'The artist mastered perspective in his drawings.', 5, $art],
            ['composition', 'ˌkɒmpəˈzɪʃən', 'композиция (художественная)', 'The composition of the painting is very balanced.', 5, $art],
            ['hue', 'hjuː', 'оттенок', 'The sunset had a beautiful orange hue.', 5, $art],
            ['shade', 'ʃeɪd', 'тон (оттенок цвета)', 'She used a darker shade of blue.', 3, $art],
            ['tint', 'tɪnt', 'оттенок (светлый)', 'A light tint of pink covered the sky.', 5, $art],
            ['symmetry', 'ˈsɪmətri', 'симметрия', 'The building has perfect symmetry.', 5, $art],
            ['proportion', 'prəˈpɔːʃən', 'пропорция', 'The artist paid close attention to proportion.', 5, $art],
            ['technique', 'tekˈniːk', 'техника (художественная)', 'He developed his own painting technique.', 4, $art],
            ['style', 'staɪl', 'стиль', 'Her artistic style is very unique.', 2, $art],
            ['movement', 'ˈmuːvmənt', 'течение (художественное)', 'Impressionism was a major art movement.', 4, $art],
            ['renaissance', 'rɪˈneɪsəns', 'ренессанс', 'The Renaissance produced many great artists.', 5, $art],
            ['impressionism', 'ɪmˈpreʃənɪzəm', 'импрессионизм', 'Monet is famous for his impressionism.', 6, $art],
            ['cubism', 'ˈkjuːbɪzəm', 'кубизм', 'Picasso helped develop cubism.', 6, $art],
            ['surrealism', 'səˈrɪəlɪzəm', 'сюрреализм', 'Dalí is famous for his surrealism.', 6, $art],
            ['realism', 'ˈrɪəlɪzəm', 'реализм', 'The novel is written in a style of realism.', 5, $art],
            ['pop art', 'pɒp ɑːt', 'поп-арт', 'Andy Warhol was a leading figure in pop art.', 5, $art],
            ['graffiti', 'ɡrəˈfiːti', 'граффити', 'The wall was covered in colourful graffiti.', 4, $art],
            ['installation', 'ˌɪnstəˈleɪʃən', 'инсталляция (арт-объект)', 'The museum featured a large art installation.', 6, $art],
            ['curator', 'kjʊəˈreɪtə', 'куратор (выставки)', 'The curator selected the paintings for the show.', 6, $art],
            ['auction', 'ˈɔːkʃən', 'аукцион', 'The painting sold at auction for a record price.', 4, $art],
            ['forgery', 'ˈfɔːdʒəri', 'подделка', 'The painting turned out to be a forgery.', 6, $art],
            ['replica', 'ˈreplɪkə', 'копия (точная)', 'This is a replica of the original statue.', 5, $art],
            ['original', 'əˈrɪdʒɪnəl', 'оригинал', 'The museum keeps the original, not a copy.', 3, $art],
            ['authentic', 'ɔːˈθentɪk', 'подлинный', 'Experts confirmed the painting was authentic.', 5, $art],
            ['aesthetic', 'iːsˈθetɪk', 'эстетический', 'The design has a very modern aesthetic.', 6, $art],
            ['creativity', 'ˌkriːeɪˈtɪvəti', 'творчество', 'The course encourages creativity in students.', 4, $art],
            ['inspiration', 'ˌɪnspəˈreɪʃən', 'вдохновение', 'Nature is her main source of inspiration.', 4, $art],
            ['imagination', 'ɪˌmædʒɪˈneɪʃən', 'воображение', 'Children have a wonderful imagination.', 4, $art],
            ['craftsmanship', 'ˈkrɑːftsmənʃɪp', 'мастерство', 'The furniture shows excellent craftsmanship.', 6, $art],
            ['artisan', 'ˈɑːtɪzæn', 'ремесленник', 'Local artisans make handmade pottery.', 5, $art],
            ['handicraft', 'ˈhændikrɑːft', 'ремесло (рукоделие)', 'She sells handicrafts at the market.', 5, $art],
            ['ceramics', 'səˈræmɪks', 'керамика', 'The exhibition includes ancient ceramics.', 5, $art],
            ['pottery', 'ˈpɒtəri', 'гончарное дело', 'He learned pottery at the local studio.', 4, $art],
            ['carving', 'ˈkɑːvɪŋ', 'резьба (по дереву/камню)', 'The wooden carving took months to finish.', 4, $art],
            ['engraving', 'ɪnˈɡreɪvɪŋ', 'гравюра', 'The book contains beautiful engravings.', 5, $art],
            ['etching', 'ˈetʃɪŋ', 'офорт', 'The artist specialised in etching.', 6, $art],
            ['printmaking', 'ˈprɪntmeɪkɪŋ', 'печатная графика', 'She studied printmaking at art school.', 6, $art],
            ['lithograph', 'ˈlɪθəɡrɑːf', 'литография', 'The gallery displayed several lithographs.', 7, $art],
            ['collage', 'ˈkɒlɑːʒ', 'коллаж', 'The children made a collage from magazine pictures.', 4, $art],
            ['mosaic', 'məʊˈzeɪɪk', 'мозаика', 'The floor is decorated with an ancient mosaic.', 5, $art],
            ['calligraphy', 'kəˈlɪɡrəfi', 'каллиграфия', 'She practises Japanese calligraphy.', 5, $art],
            ['typography', 'taɪˈpɒɡrəfi', 'типографика', 'Good typography makes a design easy to read.', 6, $art],
            ['illustration', 'ˌɪləˈstreɪʃən', 'иллюстрация', 'The book has beautiful illustrations.', 4, $art],
            ['illustrator', 'ˈɪləstreɪtə', 'иллюстратор', 'She works as a freelance illustrator.', 4, $art],
            ['cartoon', 'kɑːˈtuːn', 'мультфильм/карикатура', 'The newspaper published a political cartoon.', 3, $art],
            ['caricature', 'ˈkærɪkətʃə', 'карикатура (портрет)', 'The artist drew a caricature of the mayor.', 5, $art],
            ['doodle', 'ˈduːdl', 'машинальный рисунок', 'He was doodling in the margin of his notebook.', 4, $art],
            ['exhibit', 'ɪɡˈzɪbɪt', 'экспонат', 'The new exhibit at the museum opens next week.', 4, $art],
            ['art dealer', 'ɑːt ˈdiːlə', 'арт-дилер', 'The art dealer sold the painting to a collector.', 5, $art],
            ['art critic', 'ɑːt ˈkrɪtɪk', 'арт-критик', 'The art critic praised the new exhibition.', 5, $art],
            ['brushstroke', 'ˈbrʌʃstrəʊk', 'мазок кисти', 'You can see every brushstroke up close.', 5, $art],
            ['palette knife', 'ˈpælət naɪf', 'мастихин', 'She applied thick paint with a palette knife.', 6, $art],
            ['sketchbook', 'ˈsketʃbʊk', 'альбом для эскизов', 'He always carries a sketchbook with him.', 4, $art],
            ['muse', 'mjuːz', 'муза', 'She was the painter\'s muse for many years.', 5, $art],
            ['patron', 'ˈpeɪtrən', 'меценат', 'A wealthy patron funded the young painter\'s work.', 6, $art],
            ['restoration', 'ˌrestəˈreɪʃən', 'реставрация', 'The painting underwent careful restoration.', 6, $art],
            ['conservator', 'kənˈsɜːvətə', 'реставратор', 'A conservator repaired the damaged fresco.', 7, $art],
            ['gilding', 'ˈɡɪldɪŋ', 'позолота', 'The frame is decorated with gold gilding.', 6, $art],
            ['varnish', 'ˈvɑːnɪʃ', 'лак (для картины)', 'The painting was protected with a layer of varnish.', 5, $art],
            ['medium', 'ˈmiːdiəm', 'материал (художественный)', 'Oil paint is her favourite medium.', 5, $art],
            ['pigment', 'ˈpɪɡmənt', 'пигмент', 'The paint gets its colour from natural pigments.', 5, $art],
            ['dye', 'daɪ', 'краситель', 'The fabric was coloured with a bright dye.', 4, $art],
            ['gradient', 'ˈɡreɪdiənt', 'градиент', 'The sky showed a gradient from orange to purple.', 5, $art],
            ['vanishing point', 'ˈvænɪʃɪŋ pɔɪnt', 'точка схода', 'All the lines converge at the vanishing point.', 7, $art],
            ['foreground', 'ˈfɔːɡraʊnd', 'передний план', 'A tree stands in the foreground of the painting.', 5, $art],
            ['background', 'ˈbækɡraʊnd', 'задний план', 'The mountains form the background of the scene.', 3, $art],
            ['focal point', 'ˈfəʊkəl pɔɪnt', 'фокусная точка', 'The red flower is the focal point of the picture.', 6, $art],
            ['negative space', 'ˈneɡətɪv speɪs', 'негативное пространство', 'The artist used negative space cleverly.', 7, $art],
            ['figurative', 'ˈfɪɡərətɪv', 'фигуративный', 'He returned to figurative painting after years of abstract work.', 7, $art],
            ['monochrome', 'ˈmɒnəkrəʊm', 'монохромный', 'The photograph was printed in monochrome.', 5, $art],
            ['polychrome', 'ˈpɒlikrəʊm', 'многоцветный', 'The statue was originally polychrome.', 7, $art],
            ['seascape', 'ˈsiːskeɪp', 'морской пейзаж', 'He painted a seascape of the stormy coast.', 5, $art],
            ['cityscape', 'ˈsɪtiskeɪp', 'городской пейзаж', 'The artist is known for her cityscapes.', 5, $art],
            ['genre painting', 'ˈʒɒnrə ˈpeɪntɪŋ', 'жанровая живопись', 'Genre painting depicts scenes from everyday life.', 7, $art],
            ['folk art', 'fəʊk ɑːt', 'народное искусство', 'The museum has a collection of folk art.', 5, $art],
            ['avant-garde', 'ˌævɒŋˈɡɑːd', 'авангард', 'The gallery focuses on avant-garde artists.', 7, $art],
            ['baroque', 'bəˈrɒk', 'барокко', 'The church is decorated in the baroque style.', 6, $art],
            ['minimalism', 'ˈmɪnɪməlɪzəm', 'минимализм', 'Her work is a good example of minimalism.', 6, $art],
            ['conceptual art', 'kənˈseptʃuəl ɑːt', 'концептуальное искусство', 'Conceptual art focuses on ideas rather than objects.', 7, $art],
            ['performance art', 'pəˈfɔːməns ɑːt', 'перформанс (искусство)', 'The performance art piece lasted three hours.', 6, $art],
            ['digital art', 'ˈdɪdʒɪtəl ɑːt', 'цифровое искусство', 'Digital art is created entirely on a computer.', 4, $art],
            ['photographer', 'fəˈtɒɡrəfə', 'фотограф', 'She works as a professional photographer.', 3, $art],
            ['photograph', 'ˈfəʊtəɡrɑːf', 'фотография', 'He took a photograph of the sunset.', 2, $art],
            ['snapshot', 'ˈsnæpʃɒt', 'снимок', 'She took a quick snapshot with her phone.', 4, $art],
            ['exposure', 'ɪkˈspəʊʒə', 'экспозиция (фото)', 'A longer exposure captures more light.', 6, $art],
            ['lens', 'lenz', 'объектив', 'He switched to a wide-angle lens.', 4, $art],
            ['aperture', 'ˈæpətʃə', 'диафрагма', 'A wide aperture creates a blurred background.', 7, $art],
            ['shutter', 'ˈʃʌtə', 'затвор (камеры)', 'The shutter clicked as she took the photo.', 5, $art],
        ];
    }
}
