<?php

namespace Database\Seeders;

use App\Models\Vocabulary\Word;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Second batch of the vocabulary expansion (see VocabularyBatch1Seeder).
 * Skips any English word that already exists in the words table
 * (case-insensitive) so the seeder is safe to re-run.
 */
class VocabularyBatch2Seeder extends Seeder
{
    public function run(): void
    {
        $existing = Word::pluck('word')->map(fn ($w) => Str::lower($w))->flip();

        $created = 0;
        $skipped = 0;

        foreach ($this->entries() as $row) {
            [$en, $ipa, $ru, $example, $difficulty, $category] = $row;

            if (isset($existing[Str::lower($en)])) {
                $skipped++;

                continue;
            }

            $word = Word::create([
                'word' => $en,
                'transcription' => $ipa,
                'example' => $example,
                'difficulty' => $difficulty,
                'category' => $category,
            ]);

            $word->translations()->create([
                'language' => 'ru',
                'translation' => $ru,
                'example' => $example,
            ]);

            $existing[Str::lower($en)] = true;
            $created++;
        }

        $this->command?->info("VocabularyBatch2Seeder: +{$created} words, {$skipped} skipped as already existing.");
    }

    /**
     * @return array<int, array{0: string, 1: string, 2: string, 3: string, 4: int, 5: string}>
     */
    private function entries(): array
    {
        $biz = 'Бизнес и предпринимательство';
        $cook = 'Кулинария: методы и посуда';

        return [
            // ===== Бизнес и предпринимательство (Business and Entrepreneurship) =====
            ['startup', 'ˈstɑːtʌp', 'стартап', 'She founded a tech startup last year.', 3, $biz],
            ['entrepreneur', 'ˌɒntrəprəˈnɜː', 'предприниматель', 'He is a successful entrepreneur.', 5, $biz],
            ['funding', 'ˈfʌndɪŋ', 'финансирование', 'The company received funding from investors.', 4, $biz],
            ['venture', 'ˈventʃə', 'предприятие (рисковое)', 'They launched a new business venture.', 5, $biz],
            ['capital', 'ˈkæpɪtəl', 'капитал', 'The firm needs more capital to expand.', 5, $biz],
            ['revenue', 'ˈrevənjuː', 'выручка', 'The company\'s revenue increased last quarter.', 5, $biz],
            ['profit', 'ˈprɒfɪt', 'прибыль', 'The business made a huge profit this year.', 3, $biz],
            ['loss', 'lɒs', 'убыток', 'The company reported a loss last quarter.', 3, $biz],
            ['budget', 'ˈbʌdʒɪt', 'бюджет', 'We need to stick to the budget.', 3, $biz],
            ['expense', 'ɪkˈspens', 'расход', 'Travel expenses are covered by the company.', 4, $biz],
            ['asset', 'ˈæset', 'актив', 'Property is a valuable business asset.', 5, $biz],
            ['liability', 'ˌlaɪəˈbɪləti', 'обязательство', 'Debt is recorded as a liability.', 7, $biz],
            ['shareholder', 'ˈʃeəhəʊldə', 'акционер', 'Shareholders voted on the new proposal.', 5, $biz],
            ['stakeholder', 'ˈsteɪkhəʊldə', 'заинтересованная сторона', 'All stakeholders attended the meeting.', 6, $biz],
            ['merger', 'ˈmɜːdʒə', 'слияние', 'The merger created a much larger company.', 6, $biz],
            ['acquisition', 'ˌækwɪˈzɪʃən', 'приобретение', 'The acquisition cost billions of dollars.', 6, $biz],
            ['negotiation', 'nɪˌɡəʊʃiˈeɪʃən', 'переговоры', 'The negotiation lasted several hours.', 5, $biz],
            ['partnership', 'ˈpɑːtnəʃɪp', 'партнёрство', 'They formed a business partnership.', 4, $biz],
            ['corporation', 'ˌkɔːpəˈreɪʃən', 'корпорация', 'She works for a large corporation.', 4, $biz],
            ['enterprise', 'ˈentəpraɪz', 'предприятие', 'This is a small family enterprise.', 5, $biz],
            ['headquarters', 'ˌhedˈkwɔːtəz', 'штаб-квартира', 'The company\'s headquarters are in London.', 5, $biz],
            ['branch', 'brɑːntʃ', 'филиал', 'The bank opened a new branch downtown.', 3, $biz],
            ['subsidiary', 'səbˈsɪdiəri', 'дочерняя компания', 'The subsidiary operates independently.', 7, $biz],
            ['franchise', 'ˈfræntʃaɪz', 'франшиза', 'He bought a franchise of the coffee chain.', 6, $biz],
            ['brand', 'brænd', 'бренд', 'The brand is known worldwide.', 3, $biz],
            ['marketing', 'ˈmɑːkɪtɪŋ', 'маркетинг', 'She works in the marketing department.', 3, $biz],
            ['advertising', 'ˈædvətaɪzɪŋ', 'реклама', 'The company spends a lot on advertising.', 4, $biz],
            ['campaign', 'kæmˈpeɪn', 'кампания', 'The advertising campaign was very successful.', 4, $biz],
            ['competitor', 'kəmˈpetɪtə', 'конкурент', 'Our main competitor lowered its prices.', 4, $biz],
            ['competition', 'ˌkɒmpəˈtɪʃən', 'конкуренция', 'There is strong competition in this market.', 4, $biz],
            ['customer', 'ˈkʌstəmə', 'клиент', 'The customer was very satisfied with the service.', 2, $biz],
            ['client', 'ˈklaɪənt', 'клиент', 'The lawyer met with a new client.', 3, $biz],
            ['supplier', 'səˈplaɪə', 'поставщик', 'We changed our supplier last month.', 4, $biz],
            ['vendor', 'ˈvendə', 'продавец (поставщик)', 'The vendor delivered the goods on time.', 5, $biz],
            ['retailer', 'ˈriːteɪlə', 'розничный продавец', 'The retailer offers a wide range of products.', 5, $biz],
            ['wholesaler', 'ˈhəʊlseɪlə', 'оптовик', 'The wholesaler sells directly to shops.', 6, $biz],
            ['distribution', 'ˌdɪstrɪˈbjuːʃən', 'распределение', 'The company improved its distribution network.', 5, $biz],
            ['logistics', 'ləˈdʒɪstɪks', 'логистика', 'Logistics is a key part of the business.', 6, $biz],
            ['inventory', 'ˈɪnvəntri', 'товарные запасы', 'The shop checked its inventory before Christmas.', 5, $biz],
            ['stock', 'stɒk', 'запас (товара)', 'The item is currently out of stock.', 3, $biz],
            ['pricing', 'ˈpraɪsɪŋ', 'ценообразование', 'The company changed its pricing strategy.', 5, $biz],
            ['promotion', 'prəˈməʊʃən', 'продвижение', 'The store is running a special promotion.', 4, $biz],
            ['pitch', 'pɪtʃ', 'презентация (для инвесторов)', 'He gave a great pitch to the investors.', 5, $biz],
            ['proposal', 'prəˈpəʊzəl', 'предложение (деловое)', 'The team submitted a business proposal.', 4, $biz],
            ['deal', 'diːl', 'сделка', 'They closed the deal yesterday.', 3, $biz],
            ['CEO', 'ˌsiː.iːˈəʊ', 'генеральный директор', 'The CEO announced the new strategy.', 4, $biz],
            ['executive', 'ɪɡˈzekjʊtɪv', 'руководитель', 'She is a senior executive at the firm.', 5, $biz],
            ['milestone', 'ˈmaɪlstəʊn', 'веха', 'Reaching one million users was a big milestone.', 5, $biz],
            ['goal', 'ɡəʊl', 'цель', 'Our goal is to double sales this year.', 2, $biz],
            ['objective', 'əbˈdʒektɪv', 'задача', 'The main objective is to increase efficiency.', 5, $biz],
            ['performance', 'pəˈfɔːməns', 'результативность', 'The company\'s performance improved this year.', 4, $biz],
            ['productivity', 'ˌprɒdʌkˈtɪvəti', 'производительность', 'New tools boosted employee productivity.', 6, $biz],
            ['efficiency', 'ɪˈfɪʃənsi', 'эффективность', 'The new system improved efficiency greatly.', 5, $biz],
            ['innovation', 'ˌɪnəˈveɪʃən', 'инновация', 'Innovation drives the company\'s success.', 5, $biz],
            ['disruption', 'dɪsˈrʌpʃən', 'прорыв (в отрасли)', 'The startup caused disruption in the industry.', 6, $biz],
            ['growth', 'ɡrəʊθ', 'рост', 'The company experienced rapid growth.', 3, $biz],
            ['scalable', 'ˈskeɪləbl', 'масштабируемый', 'The business model is highly scalable.', 7, $biz],
            ['profitable', 'ˈprɒfɪtəbl', 'прибыльный', 'The new product line is very profitable.', 4, $biz],
            ['bankrupt', 'ˈbæŋkrʌpt', 'банкрот', 'The company went bankrupt last year.', 5, $biz],
            ['bankruptcy', 'ˈbæŋkrʌptsi', 'банкротство', 'They filed for bankruptcy in 2020.', 6, $biz],
            ['liquidation', 'ˌlɪkwɪˈdeɪʃən', 'ликвидация', 'The firm went into liquidation.', 7, $biz],
            ['debt', 'det', 'долг', 'The company has a lot of debt.', 3, $biz],
            ['loan', 'ləʊn', 'кредит', 'They took out a loan to expand the business.', 3, $biz],
            ['credit', 'ˈkredɪt', 'кредит (доверие)', 'The shop offers customers credit.', 3, $biz],
            ['equity', 'ˈekwɪti', 'акционерный капитал', 'Investors received equity in the company.', 6, $biz],
            ['dividend', 'ˈdɪvɪdend', 'дивиденд', 'Shareholders received a large dividend.', 6, $biz],
            ['portfolio', 'pɔːtˈfəʊliəʊ', 'портфель (инвестиций)', 'She has a diverse investment portfolio.', 6, $biz],
            ['trade', 'treɪd', 'торговля', 'International trade boosts the economy.', 3, $biz],
            ['trading', 'ˈtreɪdɪŋ', 'трейдинг', 'He works in stock trading.', 4, $biz],
            ['economic', 'ˌiːkəˈnɒmɪk', 'экономический', 'The economic situation is improving.', 4, $biz],
            ['inflation', 'ɪnˈfleɪʃən', 'инфляция', 'Inflation has increased prices significantly.', 5, $biz],
            ['recession', 'rɪˈseʃən', 'рецессия', 'The country entered a recession.', 5, $biz],
            ['tax', 'tæks', 'налог', 'The government increased income tax.', 2, $biz],
            ['taxation', 'tækˈseɪʃən', 'налогообложение', 'Taxation policy affects everyone.', 6, $biz],
            ['income', 'ˈɪnkʌm', 'доход', 'Her monthly income increased this year.', 3, $biz],
            ['salary', 'ˈsæləri', 'зарплата', 'He earns a good salary.', 2, $biz],
            ['wage', 'weɪdʒ', 'заработная плата', 'The minimum wage went up this year.', 3, $biz],
            ['bonus', 'ˈbəʊnəs', 'премия', 'She received a bonus for her hard work.', 3, $biz],
            ['commission', 'kəˈmɪʃən', 'комиссия (доход)', 'Salespeople earn a commission on every sale.', 5, $biz],
            ['freelancer', 'ˈfriːlɑːnsə', 'фрилансер', 'She works as a freelancer from home.', 4, $biz],
            ['outsourcing', 'ˈaʊtsɔːsɪŋ', 'аутсорсинг', 'The company relies on outsourcing for IT support.', 6, $biz],
            ['workplace', 'ˈwɜːkpleɪs', 'рабочее место', 'The workplace has a friendly atmosphere.', 3, $biz],
            ['employee', 'ɪmˈplɔɪiː', 'сотрудник', 'The company has over 500 employees.', 3, $biz],
            ['employer', 'ɪmˈplɔɪə', 'работодатель', 'Her employer offers great benefits.', 3, $biz],
            ['recruitment', 'rɪˈkruːtmənt', 'найм персонала', 'The recruitment process took two months.', 5, $biz],
            ['hire', 'ˈhaɪə', 'нанимать', 'The company plans to hire ten new staff.', 3, $biz],
            ['fire', 'ˈfaɪə', 'увольнять', 'He was fired after missing several deadlines.', 3, $biz],
            ['resign', 'rɪˈzaɪn', 'увольняться (по собств. желанию)', 'She decided to resign from her position.', 5, $biz],
            ['retire', 'rɪˈtaɪə', 'уходить на пенсию', 'He plans to retire next year.', 3, $biz],
            ['demotion', 'dɪˈməʊʃən', 'понижение в должности', 'His demotion came as a surprise.', 7, $biz],
            ['training', 'ˈtreɪnɪŋ', 'обучение', 'New staff receive two weeks of training.', 2, $biz],
            ['onboarding', 'ˈɒnbɔːdɪŋ', 'адаптация (новых сотрудников)', 'The onboarding process helps new hires settle in.', 6, $biz],
            ['teamwork', 'ˈtiːmwɜːk', 'командная работа', 'Good teamwork made the project a success.', 3, $biz],
            ['leadership', 'ˈliːdəʃɪp', 'лидерство', 'Strong leadership is essential in a crisis.', 4, $biz],
            ['management', 'ˈmænɪdʒmənt', 'управление', 'The company hired a new management team.', 3, $biz],
            ['delegate', 'ˈdelɪɡeɪt', 'делегировать', 'A good manager knows how to delegate tasks.', 6, $biz],
            ['supervise', 'ˈsuːpəvaɪz', 'контролировать', 'She supervises a team of ten people.', 5, $biz],
            ['quarterly', 'ˈkwɔːtəli', 'ежеквартальный', 'The company publishes quarterly reports.', 5, $biz],
            ['audit', 'ˈɔːdɪt', 'аудит', 'The firm underwent a financial audit.', 5, $biz],
            ['compliance', 'kəmˈplaɪəns', 'соответствие требованиям', 'The company ensures compliance with regulations.', 6, $biz],
            ['regulation', 'ˌreɡjʊˈleɪʃən', 'регулирование', 'New regulations affect small businesses.', 5, $biz],
            ['license', 'ˈlaɪsəns', 'лицензия', 'The company obtained a business license.', 4, $biz],
            ['patent', 'ˈpætənt', 'патент', 'They filed a patent for the new invention.', 5, $biz],
            ['trademark', 'ˈtreɪdmɑːk', 'товарный знак', 'The logo is a registered trademark.', 5, $biz],
            ['copyright', 'ˈkɒpiraɪt', 'авторское право', 'The book is protected by copyright.', 5, $biz],
            ['overhead', 'ˈəʊvəhed', 'накладные расходы', 'The company reduced its overhead costs.', 6, $biz],
            ['turnover', 'ˈtɜːnəʊvə', 'оборот (компании)', 'Annual turnover reached ten million pounds.', 6, $biz],
            ['projection', 'prəˈdʒekʃən', 'прогноз', 'Sales projections look promising for next year.', 6, $biz],
            ['benchmark', 'ˈbentʃmɑːk', 'эталон', 'The company set a new industry benchmark.', 6, $biz],
            ['procurement', 'prəˈkjʊəmənt', 'закупки', 'The procurement team negotiated better prices.', 7, $biz],
            ['sourcing', 'ˈsɔːsɪŋ', 'поиск поставщиков', 'Ethical sourcing is important to the brand.', 6, $biz],
            ['warehouse', 'ˈweəhaʊs', 'склад', 'The goods are stored in a large warehouse.', 3, $biz],
            ['wholesale', 'ˈhəʊlseɪl', 'оптовый', 'They buy products at wholesale prices.', 5, $biz],
            ['retail', 'ˈriːteɪl', 'розничный', 'She works in the retail industry.', 3, $biz],
            ['e-commerce', 'ˈiː kɒmɜːs', 'электронная коммерция', 'E-commerce has grown rapidly in recent years.', 4, $biz],
            ['subscription', 'səbˈskrɪpʃən', 'подписка', 'I have a monthly subscription to the service.', 3, $biz],
            ['satisfaction', 'ˌsætɪsˈfækʃən', 'удовлетворённость', 'Customer satisfaction is our top priority.', 4, $biz],
            ['niche', 'niːʃ', 'ниша (рынка)', 'The company found a profitable niche market.', 6, $biz],
            ['monopoly', 'məˈnɒpəli', 'монополия', 'The company has a monopoly on the market.', 6, $biz],
            ['tariff', 'ˈtærɪf', 'тариф (пошлина)', 'New tariffs raised the price of imports.', 6, $biz],
            ['import', 'ˈɪmpɔːt', 'импорт', 'The country relies heavily on food imports.', 3, $biz],
            ['export', 'ˈekspɔːt', 'экспорт', 'Oil is the country\'s main export.', 3, $biz],
            ['currency', 'ˈkʌrənsi', 'валюта', 'The local currency weakened against the dollar.', 4, $biz],
            ['exchange rate', 'ɪksˈtʃeɪndʒ reɪt', 'обменный курс', 'The exchange rate changes daily.', 5, $biz],
            ['IPO', 'ˌaɪ.piːˈəʊ', 'первичное размещение акций', 'The company held its IPO last month.', 7, $biz],
            ['insurance', 'ɪnˈʃʊərəns', 'страхование', 'The business needs proper insurance.', 4, $biz],
            ['premium', 'ˈpriːmiəm', 'страховой взнос', 'The insurance premium increased this year.', 5, $biz],
            ['collateral', 'kəˈlætərəl', 'залог', 'The house was used as collateral for the loan.', 7, $biz],
            ['mortgage', 'ˈmɔːɡɪdʒ', 'ипотека', 'They took out a mortgage to buy the house.', 5, $biz],
            ['interest', 'ˈɪntrəst', 'процент (по кредиту)', 'The bank charges high interest on loans.', 4, $biz],
            ['principal', 'ˈprɪnsəpəl', 'основная сумма долга', 'She paid off the principal early.', 7, $biz],

            // ===== Кулинария: методы и посуда (Cooking Methods and Kitchenware) =====
            ['bake', 'beɪk', 'печь (в духовке)', 'She likes to bake bread on weekends.', 2, $cook],
            ['roast', 'rəʊst', 'жарить (в духовке)', 'We roasted a chicken for dinner.', 3, $cook],
            ['grill', 'ɡrɪl', 'жарить на гриле', 'Let\'s grill some vegetables tonight.', 2, $cook],
            ['fry', 'fraɪ', 'жарить (на сковороде)', 'He fried the eggs for breakfast.', 2, $cook],
            ['steam', 'stiːm', 'готовить на пару', 'Steam the vegetables to keep the vitamins.', 3, $cook],
            ['simmer', 'ˈsɪmə', 'варить на медленном огне', 'Let the sauce simmer for ten minutes.', 4, $cook],
            ['stew', 'stjuː', 'тушить', 'She stewed the meat with vegetables.', 3, $cook],
            ['poach', 'pəʊtʃ', 'варить на медленном огне (яйцо)', 'He poached an egg for breakfast.', 5, $cook],
            ['blanch', 'blɑːntʃ', 'бланшировать', 'Blanch the almonds before peeling them.', 6, $cook],
            ['sauté', 'ˈsəʊteɪ', 'обжаривать', 'Sauté the onions until golden.', 5, $cook],
            ['marinate', 'ˈmærɪneɪt', 'мариновать', 'Marinate the chicken overnight for more flavour.', 4, $cook],
            ['season', 'ˈsiːzən', 'приправлять', 'Season the soup with salt and pepper.', 3, $cook],
            ['whisk', 'wɪsk', 'взбивать (венчиком)', 'Whisk the eggs until fluffy.', 4, $cook],
            ['chop', 'tʃɒp', 'нарезать (крупно)', 'Chop the onions finely.', 2, $cook],
            ['slice', 'slaɪs', 'нарезать ломтиками', 'Slice the bread evenly.', 2, $cook],
            ['dice', 'daɪs', 'нарезать кубиками', 'Dice the tomatoes for the salad.', 3, $cook],
            ['mince', 'mɪns', 'измельчать (мясо)', 'Mince the garlic before adding it.', 4, $cook],
            ['peel', 'piːl', 'чистить (кожуру)', 'Peel the potatoes before boiling them.', 2, $cook],
            ['grate', 'ɡreɪt', 'натирать (на тёрке)', 'Grate the cheese over the pasta.', 3, $cook],
            ['knead', 'niːd', 'месить (тесто)', 'Knead the dough for ten minutes.', 4, $cook],
            ['mix', 'mɪks', 'смешивать', 'Mix the flour and sugar together.', 1, $cook],
            ['blend', 'blend', 'смешивать (в блендере)', 'Blend the fruit into a smoothie.', 3, $cook],
            ['stir', 'stɜː', 'помешивать', 'Stir the soup occasionally.', 2, $cook],
            ['pour', 'pɔː', 'наливать', 'Pour the batter into the pan.', 2, $cook],
            ['drain', 'dreɪn', 'сливать (воду)', 'Drain the pasta once it\'s cooked.', 3, $cook],
            ['strain', 'streɪn', 'процеживать', 'Strain the sauce to remove the lumps.', 4, $cook],
            ['sprinkle', 'ˈsprɪŋkəl', 'посыпать', 'Sprinkle some herbs on top.', 3, $cook],
            ['garnish', 'ˈɡɑːnɪʃ', 'украшать (блюдо)', 'Garnish the dish with fresh parsley.', 4, $cook],
            ['serve', 'sɜːv', 'подавать (на стол)', 'Serve the soup while it\'s hot.', 2, $cook],
            ['recipe', 'ˈresəpi', 'рецепт', 'She followed the recipe exactly.', 2, $cook],
            ['ingredient', 'ɪnˈɡriːdiənt', 'ингредиент', 'Fresh ingredients make a big difference.', 3, $cook],
            ['portion', 'ˈpɔːʃən', 'порция', 'The portion size was quite large.', 3, $cook],
            ['dish', 'dɪʃ', 'блюдо', 'This is my favourite dish.', 2, $cook],
            ['cuisine', 'kwɪˈziːn', 'кухня (кулинарная традиция)', 'I love French cuisine.', 4, $cook],
            ['flavour', 'ˈfleɪvə', 'вкус (аромат)', 'The soup has a rich flavour.', 3, $cook],
            ['taste', 'teɪst', 'вкус', 'This cake has a wonderful taste.', 2, $cook],
            ['texture', 'ˈtekstʃə', 'текстура', 'The cake has a soft, fluffy texture.', 4, $cook],
            ['aroma', 'əˈrəʊmə', 'аромат', 'The aroma of fresh bread filled the kitchen.', 4, $cook],
            ['sweet', 'swiːt', 'сладкий', 'This dessert is very sweet.', 1, $cook],
            ['sour', 'ˈsaʊə', 'кислый', 'The lemon tastes very sour.', 2, $cook],
            ['bitter', 'ˈbɪtə', 'горький', 'Dark chocolate can taste bitter.', 3, $cook],
            ['savoury', 'ˈseɪvəri', 'солёный/пикантный', 'I prefer savoury snacks to sweet ones.', 4, $cook],
            ['saucepan', 'ˈsɔːspən', 'кастрюля', 'Heat the milk in a saucepan.', 3, $cook],
            ['pot', 'pɒt', 'кастрюля/горшок', 'Put the pot on the stove.', 1, $cook],
            ['oven', 'ˈʌvən', 'духовка', 'Preheat the oven to 180 degrees.', 2, $cook],
            ['stove', 'stəʊv', 'плита', 'The soup is boiling on the stove.', 2, $cook],
            ['microwave', 'ˈmaɪkrəweɪv', 'микроволновка', 'Heat the leftovers in the microwave.', 2, $cook],
            ['blender', 'ˈblendə', 'блендер', 'Use a blender to make the smoothie.', 3, $cook],
            ['mixer', 'ˈmɪksə', 'миксер', 'She used a mixer to beat the eggs.', 3, $cook],
            ['grater', 'ˈɡreɪtə', 'тёрка', 'Use a grater for the carrots.', 3, $cook],
            ['peeler', 'ˈpiːlə', 'овощечистка', 'A peeler makes peeling potatoes easier.', 4, $cook],
            ['colander', 'ˈkʌləndə', 'дуршлаг', 'Drain the pasta in a colander.', 5, $cook],
            ['sieve', 'sɪv', 'сито', 'Sift the flour through a sieve.', 5, $cook],
            ['ladle', 'ˈleɪdəl', 'половник', 'Use a ladle to serve the soup.', 4, $cook],
            ['spatula', 'ˈspætjʊlə', 'лопатка', 'Flip the pancake with a spatula.', 4, $cook],
            ['tongs', 'tɒŋz', 'щипцы', 'Use tongs to turn the meat on the grill.', 4, $cook],
            ['cutting board', 'ˈkʌtɪŋ bɔːd', 'разделочная доска', 'Chop the vegetables on a cutting board.', 3, $cook],
            ['mixing bowl', 'ˈmɪksɪŋ bəʊl', 'миска для смешивания', 'Combine the ingredients in a mixing bowl.', 3, $cook],
            ['measuring cup', 'ˈmeʒərɪŋ kʌp', 'мерный стакан', 'Use a measuring cup for accurate results.', 4, $cook],
            ['timer', 'ˈtaɪmə', 'таймер', 'Set a timer for twenty minutes.', 2, $cook],
            ['apron', 'ˈeɪprən', 'фартук', 'She wore an apron while cooking.', 3, $cook],
            ['kettle', 'ˈketl', 'чайник', 'Put the kettle on for tea.', 2, $cook],
            ['toaster', 'ˈtəʊstə', 'тостер', 'Put the bread in the toaster.', 2, $cook],
            ['refrigerator', 'rɪˈfrɪdʒəreɪtə', 'холодильник', 'Keep the milk in the refrigerator.', 3, $cook],
            ['freezer', 'ˈfriːzə', 'морозильник', 'The meat is stored in the freezer.', 3, $cook],
            ['dishwasher', 'ˈdɪʃwɒʃə', 'посудомоечная машина', 'Load the plates into the dishwasher.', 3, $cook],
            ['cupboard', 'ˈkʌbəd', 'шкафчик', 'The plates are in the cupboard.', 3, $cook],
            ['pantry', 'ˈpæntri', 'кладовая', 'We keep canned food in the pantry.', 4, $cook],
            ['baker', 'ˈbeɪkə', 'пекарь', 'The baker makes fresh bread every morning.', 3, $cook],
            ['kitchen', 'ˈkɪtʃɪn', 'кухня', 'She spends a lot of time in the kitchen.', 1, $cook],
            ['cookbook', 'ˈkʊkbʊk', 'кулинарная книга', 'She bought a new cookbook.', 3, $cook],
            ['cutlery', 'ˈkʌtləri', 'столовые приборы', 'Set the table with clean cutlery.', 4, $cook],
            ['fork', 'fɔːk', 'вилка', 'Please pass me a fork.', 1, $cook],
            ['spoon', 'spuːn', 'ложка', 'Stir the coffee with a spoon.', 1, $cook],
            ['plate', 'pleɪt', 'тарелка', 'Put the food on the plate.', 1, $cook],
            ['bowl', 'bəʊl', 'миска', 'Serve the soup in a bowl.', 1, $cook],
            ['cup', 'kʌp', 'чашка', 'She drank a cup of tea.', 1, $cook],
            ['glass', 'ɡlɑːs', 'стакан', 'Fill the glass with water.', 1, $cook],
            ['napkin', 'ˈnæpkɪn', 'салфетка', 'He wiped his mouth with a napkin.', 2, $cook],
            ['tablecloth', 'ˈteɪbəlklɒθ', 'скатерть', 'She spread a clean tablecloth on the table.', 3, $cook],
            ['starter', 'ˈstɑːtə', 'закуска', 'We ordered soup as a starter.', 3, $cook],
            ['appetizer', 'ˈæpɪtaɪzə', 'закуска', 'The restaurant serves free appetizers.', 4, $cook],
            ['leftovers', 'ˈleftəʊvəz', 'остатки еды', 'We had leftovers for lunch the next day.', 3, $cook],
            ['homemade', 'ˌhəʊmˈmeɪd', 'домашний (о еде)', 'She prefers homemade bread to shop-bought.', 3, $cook],
            ['organic', 'ɔːˈɡænɪk', 'органический', 'They only buy organic vegetables.', 4, $cook],
            ['fresh', 'freʃ', 'свежий', 'These vegetables are very fresh.', 1, $cook],
            ['frozen', 'ˈfrəʊzən', 'замороженный', 'We keep frozen food in the freezer.', 2, $cook],
            ['canned', 'kænd', 'консервированный', 'Canned tomatoes are useful for sauces.', 3, $cook],
            ['expired', 'ɪkˈspaɪəd', 'просроченный', 'Throw away the expired milk.', 4, $cook],
            ['spoiled', 'spɔɪld', 'испорченный', 'The fruit had spoiled in the heat.', 3, $cook],
            ['ripe', 'raɪp', 'спелый', 'The bananas are perfectly ripe.', 3, $cook],
            ['raw', 'rɔː', 'сырой', 'Some fish is eaten raw.', 2, $cook],
            ['cooked', 'kʊkt', 'приготовленный', 'The chicken is fully cooked.', 2, $cook],
            ['casserole', 'ˈkæsərəʊl', 'запеканка', 'She made a vegetable casserole for dinner.', 5, $cook],
            ['skillet', 'ˈskɪlɪt', 'сковорода', 'Fry the bacon in a skillet.', 4, $cook],
            ['preheat', 'ˌpriːˈhiːt', 'разогревать заранее', 'Preheat the oven before baking.', 4, $cook],
            ['defrost', 'ˌdiːˈfrɒst', 'размораживать', 'Defrost the chicken before cooking it.', 4, $cook],
            ['thaw', 'θɔː', 'оттаивать', 'Let the meat thaw overnight.', 5, $cook],
            ['ferment', 'fəˈment', 'ферментировать', 'The dough needs time to ferment.', 6, $cook],
            ['pickle', 'ˈpɪkəl', 'мариновать (в рассоле)', 'They pickle cucumbers every summer.', 4, $cook],
            ['baste', 'beɪst', 'поливать соусом (при жарке)', 'Baste the turkey every 30 minutes.', 6, $cook],
            ['glaze', 'ɡleɪz', 'глазировать', 'Glaze the cake with icing.', 5, $cook],
            ['dough', 'dəʊ', 'тесто', 'Roll out the dough with a rolling pin.', 3, $cook],
            ['batter', 'ˈbætə', 'жидкое тесто', 'Pour the batter into the pan.', 4, $cook],
            ['yeast', 'jiːst', 'дрожжи', 'Add yeast to help the bread rise.', 4, $cook],
            ['broth', 'brɒθ', 'бульон', 'The soup is made with chicken broth.', 4, $cook],
            ['gravy', 'ˈɡreɪvi', 'подливка', 'Pour the gravy over the mashed potatoes.', 4, $cook],
            ['sauce', 'sɔːs', 'соус', 'The pasta comes with a tomato sauce.', 2, $cook],
            ['condiment', 'ˈkɒndɪmənt', 'приправа', 'Ketchup is a popular condiment.', 5, $cook],
            ['seasoning', 'ˈsiːzənɪŋ', 'приправа (в целом)', 'Add seasoning to taste.', 4, $cook],
            ['herb', 'hɜːb', 'трава (пряная)', 'Fresh herbs make the dish taste better.', 3, $cook],
            ['spice', 'spaɪs', 'специя', 'The curry has many spices.', 3, $cook],
            ['pinch', 'pɪntʃ', 'щепотка', 'Add a pinch of salt.', 3, $cook],
            ['tablespoon', 'ˈteɪbəlspuːn', 'столовая ложка', 'Add two tablespoons of oil.', 3, $cook],
            ['teaspoon', 'ˈtiːspuːn', 'чайная ложка', 'Add a teaspoon of sugar.', 3, $cook],
            ['buffet', 'ˈbʊfeɪ', 'фуршет', 'The hotel offers a breakfast buffet.', 4, $cook],
            ['banquet', 'ˈbæŋkwɪt', 'банкет', 'They held a banquet for the wedding.', 5, $cook],
            ['platter', 'ˈplætə', 'блюдо (большая тарелка)', 'She served a platter of cheese and fruit.', 5, $cook],
            ['tray', 'treɪ', 'поднос', 'Carry the drinks on a tray.', 2, $cook],
            ['lid', 'lɪd', 'крышка', 'Put the lid on the pot.', 2, $cook],
            ['handle', 'ˈhændl', 'ручка (посуды)', 'Be careful, the pan handle is hot.', 2, $cook],
            ['nonstick', 'ˌnɒnˈstɪk', 'антипригарный', 'This nonstick pan is easy to clean.', 4, $cook],
            ['stainless steel', 'ˌsteɪnləs ˈstiːl', 'нержавеющая сталь', 'Stainless steel pots last a long time.', 5, $cook],
            ['cast iron', 'kɑːst ˈaɪən', 'чугун', 'Cast iron skillets heat very evenly.', 5, $cook],
            ['food processor', 'fuːd ˈprəʊsesə', 'кухонный комбайн', 'Use a food processor to chop the vegetables.', 4, $cook],
            ['can opener', 'kæn ˈəʊpənə', 'консервный нож', 'We need a can opener for these beans.', 3, $cook],
            ['corkscrew', 'ˈkɔːkskruː', 'штопор', 'Use a corkscrew to open the wine bottle.', 4, $cook],
        ];
    }
}
